version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run: update-function-code -function-name grimm_skill_jovo --zip-file bundle.zip"
workflows:
    aws-cli:
      jobs:
        - aws-cli-example