version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    filters:
      branches:
        only:
          - master
    executor:
      name: node/default
    steps:
      - checkout
      - aws-cli/setup
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run bundle
      - run: aws lambda update-function-code --function-name grimm_skill_jovo --zip-file fileb://bundle.zip
 
workflows:
    aws-cli:
      jobs:
        - build-and-deploy:
            filters:
              branches:
                only:
                  - master