version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-cli: circleci/aws-cli@0.1.20
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run bundle
workflows:
    aws-cli:
      jobs:
        - aws-cli-example:
            context: aws
    build-and-test:
      jobs:
        - build-and-test